app/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('',ModeloView.as_view(),name="modelo_list"),   
    path('new',ModeloNew.as_view(),name="new"),
    path('edit/<int:pk>',ModeloEdit.as_view(),name="edit"), 
    path('crud',Crud.as_view(),name="crud"),
    path('crud/update',update1,name="update1"),
    path('crud/reload',reload,name="reload"),
    path('delete/<int:pk>',ModeloDel.as_view(),name="delete"), 
]

dj_deploy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('app.urls','app'), namespace='app')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.
class Modelo(models.Model):
    codigo=models.CharField("Código",max_length=10,unique=True)
    descripcion=models.CharField("Descripción",max_length=50)

    def __str__(self):
        return self.codigo
    
    class Meta:
        verbose_name_plural= "Modelos"

        

app/forms.py
from django import forms

from .models import *

class ModeloForm(forms.ModelForm):
    class Meta:
        model= Modelo
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            }) 

app/views.py
from django.http import JsonResponse
from django.shortcuts import render,HttpResponse
from django.views import generic
from django.urls import reverse_lazy

from .models import *
from .forms import *

class ModeloView(generic.ListView):
    permission_required = "app.view_modelo"
    model = Modelo
    template_name = "app/modelo_list.html"
    context_object_name = "obj"

class ModeloNew(generic.CreateView):
    permission_required="app.add_modelo"
    model=Modelo
    template_name="app/modelo_form.html"
    context_object_name = "obj"
    form_class=ModeloForm
    success_url=reverse_lazy("app:modelo_list")
    

class ModeloEdit(generic.UpdateView):
    permission_required="app.change_modelo"
    model=Modelo
    template_name="app/modelo_form.html"
    context_object_name = "obj"
    form_class=ModeloForm
    success_url=reverse_lazy("app:modelo_list")
    success_message="Modelo Actualizado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ModeloDel(generic.DeleteView):
    permission_required="app.delete_modelo"
    model=Modelo
    template_name='app/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("app:modelo_list")
    success_message="Modelo Eliminado Satisfactoriamente"


class Crud(generic.TemplateView):
    template_name = "app/crud.html"


def update1(request):
    if request.POST:
        c = request.POST.get("codigo")
        d = request.POST.get("desc")

        print(c,d)
        o = Modelo.objects.filter(codigo=c).first()
        if o:
            o.descripcion = d
        else:
            o = Modelo(
                codigo = c,
                descripcion = d
            )
        o.save()

        return HttpResponse("OK")
    return HttpResponse("Método No Permitido")


def reload(request):
    context = {}
    registros = Modelo.objects.all()
    context["datos"] = list(registros.values("id","codigo","descripcion").order_by("codigo"))
    return JsonResponse(context,safe=False)

app/templates/app/crud.html
{% extends 'bases/index.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Código</th>
            <th scope="col">Descripción</th>
            <th scope="col">Acción</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>    
    </div>
    <div class="col-6">
      <div class="row">
        <div class="col-2">
          <input type="text" id="id" class="form-control" placeholder="Id" readonly>
        </div>
        <div class="col-4">
          <input type="text" id="codigo" class="form-control" placeholder="Código">
        </div>
        <div class="col-6">
          <input type="text" id="descripcion" class="form-control" placeholder="Descripción">
        </div>
      </div>
      <hr class="mt-3 mb-3"/>
      <div class="row">
        <div class="col">
          <button type="button" id="add-row" class="btn btn-warning">Agregar</button>
          <button type="button" class="btn btn-info" id="btnCancel">Cancelar</button>
          <button type="button" class="btn btn-danger" id="btnSave">Guardar</button>
          <button type="button" class="btn btn-default" id="btnReload">Cargar</button>
          <button type="button" class="btn btn-success" id="btnEdit">Editar</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

{% block js%}
<script>
  $(document).ready(function(){
    recargar()
  })
  $("#add-row").click(function(){
    var codigo = $("#codigo").val();
    var desc   = $("#descripcion").val();
    var html = `<tr><td></td><td>${codigo}</td><td>${desc}</td><td>
      <button class='btn btn-danger btn-sm btn-delete' 
      >D</button>
      <button class='btn btn-success btn-sm' 
      >E</button>
      </td></tr>`
    // console.log(html)
    if(codigo==""){
      alert("Código Requerido")
      $("#codigo").focus()
      return
    }
    if(desc==""){
      alert("Descripción Requerida")
      $("#descripcion").focus()
      return
    }
    $("table tbody").append(html)
    limpiar()
  })

  $("#btnSave").click(function(){
    $("table tbody>tr").each(function (){
      var self = $(this)
      var codigo = self.find("td:eq(1)").text().trim()
      var desc = self.find("td:eq(2)").text().trim()
      var result = codigo + " " + desc
      // console.log(self)
      
      // var data = {"codigo":codigo,"desc":desc,"csrfmiddlewaretoken" : "{{csrf_token}}"}
      var data = {"codigo":codigo,"desc":desc}
      console.log(data)

      $.ajax({
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        url:"{% url 'app:update1'%}",
        data:data,
        type:"POST",
        success: function(r){

        },
        error: function(jqXHR,textStatus,error){
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("FINALIZADO")
          recargar()
        }
      })
    })
  })

  function recargar(){
    $.ajax({
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        url:"{% url 'app:reload'%}",
        type:"GEST",
        success: function(r){
          console.log(r)
          datos = r.datos;
          console.log(datos)

          $("table > tbody").empty()
          var tabla = $("table")

          var rows = $.map(datos,function(value,index){
            return `<tr>
            <td>${value.id}</td><td>${value.codigo}</td>
            <td>${value.descripcion}</td>
            <td><button class='btn btn-danger btn-sm btn-delete'
              onClick="borrar(${value.id})"
              >D</button>
              <button class='btn btn-success btn-sm' 
              onClick="paraEditar(${value.id},'${value.codigo}','${value.descripcion}')"
              >E</button>
              </td>
            </tr>`
          })
          $("table > tbody").html(rows.join(''))
        },
        error: function(jqXHR,textStatus,error){
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("FINALIZADO")
        }
      })
  }

  $("#btnReload").click(function(e){
    recargar()
  })

  function borrar(id){
    var url = `delete/${id}`

    $.ajax ({
        url : url,
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        type: "POST",
        success: function(r){
          alert("Borrado")
        },
        error: function(jqXHR,textStatus,error)
        {
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("Finalizada")
          recargar()
        }
      })
  }

  function limpiar(){
    $("#codigo").val("")
    $("#descripcion").val("")
    $("#id").val("")
    $("#codigo").focus()
  }

  function paraEditar(id,cod,desc)
  {
    limpiar()
    $("#id").val(id)
    $("#codigo").val(cod)
    $("#descripcion").val(desc)
  }

  $("#btnEdit").click(function(e){
    var cod = $("#codigo").val()
    var des = $("#descripcion").val()
    var id  = $("#id").val()

    var url = `edit/${id}`
    var data = {"codigo":cod,"descripcion":des}

    $.ajax ({
        url : url,
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        type: "POST",
        data: data,
        success: function(r){
          alert("Editado")
        },
        error: function(jqXHR,textStatus,error)
        {
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("Finalizada")
          limpiar()
          recargar()
        }
      })

  })
  $("#btnCancel").click(function(e){
    limpiar();
  })
</script>
{% endblock%}

app/templates/app/modelo_form.html
{% extends 'bases/index.html' %}

{% block content %}
<form method="post">
  <fieldset>
    <legend>
      {% if not obj %}Nuevo{%else%}Editar{% endif%}
    </legend>
    {%csrf_token%}
    {{form}}
    
    <button type="submit" class="btn btn-primary">Guardar</button>
  </fieldset>
</form>
{% endblock%}

app/templates/app/modelo_list.html
{% extends 'bases/index.html' %}

{% block content %}
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Código</th>
        <th scope="col">Descripción</th>
        <th scope="col">Acción</th>
      </tr>
    </thead>
    <tbody>
    {% for item in obj %}
      <tr>
          <td>{{item.id}}</td>
          <td>{{item.codigo}}</td>
          <td>{{item.descripcion}}</td>
          <td>
            <a href="{% url 'app:edit' item.id %}" class="btn btn-block btn-info">Editar</a>
          </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock%}

templates/bases/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Para Hacer Deploy</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <h4 class="alert-heading">Atención</h4>
        <p class="mb-0">Este proyecto forma parte del curso Deploy Django en Udemy, elaborado por Daniel Bojorge, <a href="https://facebook.com/debsconsultores" target="_blank" class="alert-link">Síguenos</a>.</p>
      </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Deploy DJ</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'app:modelo_list' %}">Lista
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:new' %}">Nuevo</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:crud' %}">Crud</a>
                </li>
              </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <div class="row">
          {% block content%}
          {% endblock %}
        </div>
      </div>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

      {% block js%}{% endblock%}
</body>
</html>